//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.15 at 10:20:30 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.yaromich.com/catmarket/ws/categories", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.yaromich.catmarket.ws.soap.categories;
